### ISSUE TITLE
What needs modified when changing the port used for NGINX container?

### ISSUE THREAD

**Issue by benbkk** [10up/wp-local-docker#101]
Hello,
How could we change the port to not use port 80?

Thanks

**Comment by pattonwebz** [comment]
Hey @benbkk,

I'm assuming you mean that you want to prevent it binding to port 80 on the host but if you mean something else let me know :)

There's a couple of options to make this happen depending on your needs but the simplest option by far is to just map it to a different port on the host.

That's done with `ports` section of a container in the `docker-compose.yml` file here: https://github.com/10up/wp-local-docker/blob/b342966087658526613f6c9e03c146e4b6bc77e8/docker-compose.yml#L55

The left side is the port it will bind to on the host, the right side is the port it maps to inside the container. You can map it to something like this: `8080:80` and that way it will bind to port `8080` on your host but forward to port `80 inside the container. You would need to specify the port number in your browser when connection like so: http://localhost:8080

Let me know if that solves your needs.

Edit: sidenote - if you are connection via the https method on port 443 then you can probably get away with not explicitly binding port 80 on the host at all by changing the ports line for it to just `80` (with no `:` and only a single port specified).

**Comment by benbkk** [comment]
Hi @pattonwebz 
Yes that is exactly my question i just didnt know how to say it 😆

Ok turned out I was doing the right thing 8080:80 but didnt work. But that's maybe because I do docker-compose up on top of that again. I'll try again. Awesome work with all the wordpress by the way, thanks!

**Comment by pattonwebz** [comment]
Yeah if you bring the containers up again when they are already up I don't think they would update ports. Best to stop the them first and bring them back up again to make sure the new config takes hold.

```
docker-compose stop
docker-compose up -d
```

I'm gonna close out this issue just now as resolved but feel free to reopen it if changing the ports like this still does not work for you.

**Comment by benbkk** [comment]
Hi  @pattonwebz 
Got it working thanks - but in addition to that, i need to update the setup.sh as well otherwise all assets are gone. 
Its working ok now, but just checking - Is there any other files that you think should be updated when changing the port number?
Thanks

**Comment by pattonwebz** [comment]
Sorry I am not certain what else might need updated if you changed ports. I'll reopen the issue and change the title. Maybe someone else will have a better idea of what would need done.

**Comment by benbkk** [comment]
@pattonwebz yes its not just updating the docker-compose.yml and bin/setup.sh: 
**docker-compose.yml**
```
nginx:
   ....
    ports:
      - "8080:80"
      - "443:443"
```
**bin/setup.sh** 
```
if [ "y" = "$MULTISITE" ]
then
...
else
	docker-compose exec --user www-data phpfpm wp core install --url=localhost:8080 --title="$TITLE" --admin_user="$ADMIN_USER" --admin_email="$ADMIN_EMAIL" --admin_password="$ADMIN_PASSWORD"
fi
```

It works but wp-admin is still referencing port 80. So this works fine
```
http://localhost:8080/wp-admin 
```
But then if you visit the site from the admin, it doesnt work because any links from admin to the site are going to port 80

**Comment by cmmarslender** [comment]
if you had the site set up on port 80 and then changed to port 8080, a search and replace will probably help fix that issue.

from the root of wp-local-docker, try running the following command:

`./bin/wp.sh search-replace localhost localhost:8080`
