### ISSUE TITLE
Move to a config that sets no explicit port binds on the host

### ISSUE THREAD

**Issue by pattonwebz** [10up/wp-local-docker#102]
Not binding to the ports directly on the host means that existing services on the host bound to the ports are not a problem to work around - as well as making it possible to run more than 1 stack of these containers at the same time.

ENV vars and/or labels might be needed on the containers to help identify them. Also explicitly defined networking or hostname aliases might be a good option to make sure that each container is talking to it's expected partner and avoid the round-robin effect when more than 1 container with the same hostname is on the same network.

Some potentially blocking considerations:

- Scripts contain `localhost` as expected url for the site, would need modified in those scripts to be more configurable.
- This method requires that an entry be added to the local machines hosts file pointing to the IP of the NGINX container (which if not explicitly defined in the networking of the config differs on each container start - needs to have a static IP assigned for this to be viable).

**Comment by JodiWarren** [comment]
Do you think that a new tool or extending https://github.com/10up/project-scaffold might be a good way to handle this? I haven't yet got my head around networks so I'm not sure if that's the right way to do it.

**Comment by kopepasah** [comment]
@pattonwebz while I have not used it personally, you can set an [overrides file](https://github.com/10up/wp-local-docker#docker-compose-overrides-file), allowing you to customize your local configuration.

**Comment by pattonwebz** [comment]
@kopepasah that works great for changing _most_ things but it also requires making changes to the setup scripts as well to prevent it from assuming the services will all be available through `localhost`.

My preference would be to decouple the need for any host binding so that no specific posts are tied up on the host machine which would allow the possibility of 2 projects and their container stacks to run concurrently without needing lots of tweaking to each project configs to make it happen.

To do that would require a pretty significant change to the general makeup of the repo and it's compose files so I opened this issue to collect thoughts/opinions :smile:

**Comment by tlovett1** [comment]
@cmmarslender is working on something so you can run more than one instance at once.

I'm not a networking expert, but I don't understand how you can run a web server without binding to a port.

**Comment by pattonwebz** [comment]
I'm looking forward to what is being worked on by @cmmarslender :)

@tlovett1 If you look at each container as it's own entity it has a dedicated virtual IP address assigned to it (which is where the ports get bound). Docker networking layer then maps the virtual IP and port bound on it to the host. All of that happens transparently in dockers networking layer. Since it is transparently done there is no need to explicitly state which port on localhost it binds to because you will still get a reply if you request on the virtual IP with the port that is expected (IE webserver on port 80, mysql on 3306 etc).

![screenshot from 2018-08-28 20-06-58](https://user-images.githubusercontent.com/3902039/44745676-4e7d8a00-ab00-11e8-8f82-8cc8be102303.png)
The screenshot above shows that I have 2 containers running. On local host they are bound to ports 32770 and 32768 but that doesn't matter because docker has mapped those to port 3306 and 80 respectively inside the containers.

To access those containers I request either via the IP directly or by a hostname I have specified in my development machines `hosts` file that points to the IP of the container.

Sorry if my explanation doesn't help you understand any better, I am also not a networking expert :stuck_out_tongue:

**Comment by cmmarslender** [comment]
Spoke with @pattonwebz a bit in slack, and his suggestion above relies on some host networking changes as well, which is probably a bit too complicated for the scope of this project.
