### ISSUE TITLE
prerequisite: first-time users, `docker login`

### ISSUE THREAD

**Issue by krisgale-zz** [10up/wp-local-docker#104]
not sure if it's appropriate within the scope of this project's readme, but as part of initial setup, first-time users of docker and docker-compose will need to run `docker login` with their Docker ID in order to establish credentials to pull/push images. (and will have created a Docker ID in order to download Docker itself.)

**Comment by cmmarslender** [comment]
Authentication is not required for pulling public images. Since all you need to do as a user of this project is pull public images, this is probably not the place for that kind of documentation.
