### ISSUE TITLE
subjectAltName, implement v3 Certificate Extensions

### ISSUE THREAD

**Issue by krisgale-zz** [10up/wp-local-docker#105]
Chrome and other A-grade browsers now report **Subject Alternative Name Missing** for certificates that do not specify subjectAltName in v3 Certificate Extensions...
i've documented how to resolve this, here:
https://internal.10up.com/docs/self-signed-ssl-cert-w-subjectaltname-for-development-use/

**Comment by jeffpaul** [comment]
@krisgale  note that we're archiving WP Local Docker in favor of the newer [WP Local Docker v2](https://github.com/10up/wp-local-docker-v2), so please update to the v2 version and we can discuss any further issues you see in its respective repo.  Thanks!
