### ISSUE TITLE
Makefile for easier docker commands

### ISSUE THREAD

**Issue by petenelson** [10up/wp-local-docker#106]
On some projects, I've created a Makefile in order to easily run various docker commands, such as `make start` to run docker compose and startup the containers, `make wp` to run bash and allow WP-CLI commands to be executed, etc.  If this sounds like it would be useful, I can submit a PR with a Makefile for running commonly-used commands.

**Comment by cmmarslender** [comment]
Can you explain a bit more the benefits that we'd gain over just running the docker-compose commands (`make start` vs `docker-compose up`, etc) directly? I'd hate to add another dependency for people to install just to get a working env.

**Comment by petenelson** [comment]
Whoops, hadn't noticed the shell scripts in /bin.  Perhaps a few more instead of a makefile...

- ./bin/start.sh
- ./bin/stop.sh
- ./bin/mysql.sh

**Comment by kopepasah** [comment]
@petenelson glad you found the bin! Do you have specific suggestions for any other scripts or commands?

**Comment by petenelson** [comment]
@kopepasah here's a PR for additional bin helper commands https://github.com/10up/wp-local-docker/pull/129

**Comment by cmmarslender** [comment]
Suggest using WP Local Docker V2, which has all kinds of helper commands like this :)
