### ISSUE TITLE
What determines XDebug's path?

### ISSUE THREAD

**Issue by emeaguiar** [10up/wp-local-docker#110]
I notices my installation couldn't find xdebug, and seeing at #86 it's happened before, but I seem to have an older version, is this based on what's on my computer?

**Comment by moraleida** [comment]
@emeaguiar the path is automatically chosen by pecl when xdebug is installed. Afaik, the timestamp identifies which PHP build is being used. We can't change this on our images, but I've created a workaround so we don't need to keep updating that reference to work with it.

**Comment by cmmarslender** [comment]
Closing. Fixed in https://github.com/10up/wp-local-docker-images/pull/9 and #111
