### ISSUE TITLE
How to enable localtunnel or ngrok (or something for tunnel)

### ISSUE THREAD

**Issue by jrhager84** [10up/wp-local-docker#113]
I *love* this image, but can't for the life of me figure out how to enable ngrok or localtunnel in the setup so that I can show clients previews of local sites over the internet. Please help, thanks!

**Comment by cmmarslender** [comment]
Since the containers bind to ports on the host, any time I've needed to use ngrok, I've run it on the host, rather than in docker.

**Comment by jrhager84** [comment]
Can you elaborate on how you use it? Maybe I'm using it incorrectly with Docker. Thanks a million!

**Comment by cmmarslender** [comment]
Once you have wp-local-docker up and running (and you can see WP running on localhost) you can do `ngrok http 80`

Once started, it will give you output like

```
Forwarding                    http://abc123.ngrok.io -> localhost:80                                                                                                            
Forwarding                    https://abc123.ngrok.io -> localhost:80       
```

and you should be able to access the site at the provided ngrok.io address. If you already went through the WordPress install, it will probably try and redirect you to localhost or a custom host name if you have it in your hosts file, so make sure to either do a search/replace, or else do the WordPress setup from the ngrok domain to get the correct site url in the database.

**Comment by jrhager84** [comment]
So, would I add that in the docker-compose file to make sure ngrok is always running when the container is running?

**Comment by cmmarslender** [comment]
I've never run ngrok in a container, I usually just run it on the host (my laptop)

**Comment by jrhager84** [comment]
Do you just make sure it's always running? Wouldn't it break the container if not running?

**Comment by cmmarslender** [comment]
The container will run either way and bind to your local machine's port 80. Running ngrok just forwards traffic from the internet to your machine

**Comment by jrhager84** [comment]
I thought you had to change the site url in the config file

**Comment by cmmarslender** [comment]
Shouldn't need to change any URLs in the config file.. nginx is set up to listen to any url on port 80. The only place you might need to change it is if your wp_options table doesn't have the ngrok url.
