### ISSUE TITLE
could you tell me how to update docker-compose to a newer version

### ISSUE THREAD

**Issue by rahulsahu95** [10up/wp-local-docker#115]
iam trying to execute mt docker-compose file,but getting error like this
ERROR: Version in "./docker-compose-appstack.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

-- can you help me out anyone,how to resolve it

**Comment by cmmarslender** [comment]
Installation instructions are available here: https://docs.docker.com/compose/install/
