### ISSUE TITLE
Import existing site db

### ISSUE THREAD

**Issue by Dave-Lindberg** [10up/wp-local-docker#119]
I have some revisions to do on an existing site, and would like to replicate it on localhost. 

When logged in using the Default WordPress admin credentials (Username: admin, Password: password), PHPmyadmin shows "No Privileges", so I'm not sure how to import my legacy db dump.

**Comment by pattonwebz** [comment]
If you do not need what is currently inside the database that's in the container then you could destroy the DB container (and remove it's volumes) and let it rebuild with a fresh one using your .sql file. 

See here in the Initialising a fresh instance section: https://hub.docker.com/_/mysql/

**Comment by christianc1** [comment]
@Dave-Lindberg ,

When logging into PHPMyAdmin, you need to use the MySQL username and password, which by default are `wordpress`/`password`, not the WP-Admin username and password.

**Comment by bjorn2404** [comment]
Just noting that you can log in to phpMyAdmin with `root / password` , which allows you to create additional databases whereas logging in with the `wordpress` username does not give you the correct privileges to do that.
