### ISSUE TITLE
Converting WP Snapshots to run instead of exec?

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/wp-local-docker#125]
Hi there!

I was wondering if it would make sense to convert WP Snapshots to be started by a `run` command that operates on a seperate Compose file. That way, when `docker-compose up` is run, it doesn't automatically bring up Snapshots unless there's a need for it.

The advantage there is there's not an extra PHP container floating around, which matters if you're trying to minimize resource usage. There's a slight hit to speed when running Snapshots commands, but it should be minimal.

Happy to submit a PR if there's a desire!

Thoughts?

**Comment by pattonwebz** [comment]
:+1:

Running containers only when needed and exiting when they complete seems like a good general practice to follow where we can.

**Comment by cmmarslender** [comment]
Looking at resource usage (`docker stats`), the wpsnapshots container idles near zero CPU usage and only about 1.5MiB memory usage. Even though its based on the php image, we change the run command to not run phpfpm, so there aren't any idle php processes lying around to take up too many resources.

**Comment by tlovett1** [comment]
Saving resources is good, but the reality of the team is many people struggle to figure out WP Snapshots. We need it to be as simple as possible and requiring people to spin up another container first is pushing us in the wrong direction.

If we can do this without adding extra steps/complexity, I'm onboard.

**Comment by ChaosExAnima** [comment]
@tlovett1 - I see no reason why we can't just have the same bash commands we currently use bring up the container automatically via `run` instead of the `exec` it currently uses?

@cmmarslender - True. My current use case is where I have multiple WP Local Docker setups running on my machine at once, so they start adding up a bit. I realize in the standard use case Snapshots doesn't take a lot.

**Comment by cmmarslender** [comment]
WP Local Docker V2 runs snapshots more along the lines of what is being requested here.
