### ISSUE TITLE
./bin/setup.sh does not have write permissions in /var/www/html in CentOS

### ISSUE THREAD

**Issue by TheLastCicada** [10up/wp-local-docker#127]
In the README, we say....

```4. Run setup to download and install WordPress.
    i. On Linux / Unix / OSX, run sh bin/setup.sh.
    ii. On Windows, run .\bin\setup.
```

On CentOS 7.5, when I run `sh bin/setup.sh`, I get the following error:

```# sh bin/setup.sh
Do you want a multisite installation? [y/n] n
Error: '/var/www/html/' is not writable by current user.
```

I'm running everything as the root user in CentOS.  When I SSH to the PHP container, I can run all of the wp-cli commands to download and install core as the root user of the container and they work fine.    If I look at the permissions on the `/var/www/html` folder in the container, it looks like the setup.sh script would have to run wp-cli as root in the container for it to work:

```drwxr-xr-x  2 root     root      44 Aug 25 22:38 html```

Some very brief research would suggest running the setup.sh script as root and then doing a `chown -R www-data /var/www/html` at the end of the script would make everything work as expected.

**Comment by cmmarslender** [comment]
Resolved in 612aceb
