### ISSUE TITLE
docker-compose doesn't get passed mysql setup

### ISSUE THREAD

**Issue by chuckreynolds** [10up/wp-local-docker#13]
I've ran this 3 times now... always hangs with this as the last line in terminal:
`mysql_1          | 2017-05-02T03:04:51.764010Z 0 [Note] End of list of non-natively partitioned tables`

thoughts?

**Comment by thadroe** [comment]
From what I'm seeing that looks perfectly normal to me if you ran `docker-compose up`. That particular output line is the very last thing it shows on my end too even if it's running fine. It only appears hung because it's running in the terminal and continuously displaying the output of the containers.

Try it with `docker-compose up -d` instead to run it in detached mode in the background.

**Comment by chuckreynolds** [comment]
well it wouldn't complete. Opt+C led to:
```
flushed=0 and evicted=0, during the time.)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping wpdockertest_nginx_1 ... done
Stopping wpdockertest_phpfpm_1 ... done
Stopping wpdockertest_elasticsearch_1 ... done
Stopping wpdockertest_mysql_1 ... done
Stopping wpdockertest_memcached_1 ... done
```

I ran the `-d` flag and that was much.... MUCH faster. ;)  thx

**Comment by tlovett1** [comment]
Running the process in the foreground is pretty helpful as it will show you errors as they happen.

**Comment by chuckreynolds** [comment]
is it meant to be open like that? like a tail ?  
I just wasn't aware of that, hence the issue. Maybe a mention of it in the readme?

**Comment by thadroe** [comment]
Yes with `docker-compose up` it's meant to be open. You can see more here on the [docker-compose up docs](https://docs.docker.com/compose/reference/up/).

`docker-compose up -d` just shoves it to the background, although you can still print the same output on a one-off basis if you'd like with `docker-compose logs`.

There's no right or wrong there, just a different preference on how people like to use it.

**Comment by chuckreynolds** [comment]
copy that. i'm used to vagrant up. Thx guys.
