### ISSUE TITLE
Consider replacing Mailcatcher with Mailhog

### ISSUE THREAD

**Issue by aaemnnosttv** [10up/wp-local-docker#132]
[Mailhog](https://github.com/mailhog/MailHog) is a newer project inspired by Mailcatcher, written in Go.

Apart from it's more pleasing aesthetic appearance, I believe it offers some features and benefits that Mailcatcher does not.

- native notifications on MacOS (maybe others too?) when inbox is open
- exposes an API for fetching messages programmatically
- can "release" messages to a real SMTP server for delivery
- in memory or persistent message storage
- offers a replacement for `sendmail`
- easy to install + configure in Docker https://registry.hub.docker.com/u/mailhog/mailhog/

It may also be worth noting that Flywheel's Docker-based "Local" development environment switched from Mailcatcher to Mailhog as part of its [2.0 release](https://local.getflywheel.com/community/t/local-by-flywheel-2-0-1/1547).

I would be happy to contribute a PR if the powers that be would be open to consider one?

**Comment by tlovett1** [comment]
Hey @aaemnnosttv, I'm onboard with this. However, we are in the process to switching to WP Local Docker V2 (which will be noted in this repo but isn't yet). Want to move this issue to https://github.com/10up/wp-local-docker-v2 ?

Really appreciate you recommending this!

**Comment by aaemnnosttv** [comment]
Thanks! I'll open a new issue on that repo.

**Comment by cmmarslender** [comment]
Closed in favor of the issue on the V2 repo
