### ISSUE TITLE
Is wp-cli a dependancy?

### ISSUE THREAD

**Issue by dhuyvetter** [10up/wp-local-docker#134]
The documentation only mentions docker and docker-compose as dependencies, but before I installed wp-cli locally the `sh bin/setup.sh` command failed. After I installed wp-cli it ran without a problem.

**Comment by cmmarslender** [comment]
Good question. Its not specifically required to just use the docker-compose configuration, but if you want to use the setup scripts to automatically install WordPress, it would be required. It was added after the fact, and readme probably was never updated. I'd welcome a PR for a simple readme fix if you'd like, but overall this version is not actively being worked on. We have a V2 of WP Local Docker that you can check out - [Documentation here](https://10up.github.io/wp-local-docker-docs/)
