### ISSUE TITLE
Any idea why is so slow?

### ISSUE THREAD

**Issue by blonestar** [10up/wp-local-docker#136]
I test this with empty WP and getting time to first bite (TTFB) around 600ms which, I believe, is slow.
With docker-php-ext-xdebug.ini turned on is almost 2sec.
In some other environments I'm getting TTFB in ~80-200ms, talking about empty WP installation.

My computer is Ryzen7 with 8 cores, 16gb RAM and M.2 SSD (read 3.5gb/s) so that cannot be an issue.
I like this environment and would like to find out where is the bottle neck.

thanks
Bojan

**Comment by mayteio** [comment]
+1. even after turning off xdebug

**Comment by cmmarslender** [comment]
Changes in 88716cb should help with slowness
