### ISSUE TITLE
I can get to my site via <project>.test, but I get a 503 on localhost.

### ISSUE THREAD

**Issue by palomnik** [10up/wp-local-docker#140]
<project>.test works just fine, but I would like to use something like localhost, or even better, machine.local, so that I can check the site with my phone, or temporarily share it with another stakeholder via ngrok.

It seemed like this was working, the first time I started the container, but now it does not.

**Comment by palomnik** [comment]
I rebooted, and now I can't get to my site either - just the "welcome to nginx" message.

**Comment by jeffpaul** [comment]
@palomnik  note that we're archiving WP Local Docker in favor of the newer [WP Local Docker v2](https://github.com/10up/wp-local-docker-v2), so please update to the v2 version and we can discuss any further issues you see in its respective repo.  Thanks!
