### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by joecue** [10up/wp-local-docker#15]
I am unable to get the containers up and running.  I'm using Docker on Windows 7, so it's using the Docker Toolbox.  Seems like I should still be able to make this run though.  I'm getting the following error

ERROR: for elasticsearch  Cannot start service elasticsearch: oci runtime error: container_linux.go:247: starting container proces
s caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/c/www-root/docker-local/joequerin/config
/elasticsearch/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/4537718fbff08171f42c5a47efae7c45e78fe8a3723af
919351c4e4407db5bc3\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/4537718fbff08171f42c5a47efae7c45e78fe8a3723af919351c4e4407db5bc3/
usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

When I run "docker ps" I see the memcache container and mysql running, but no nginx or other containers.

Any ideas?

**Comment by ivankristianto** [comment]
I'm guessing you have the port used for another service.
It's good if you start your docker compose in foreground mode. just strip `-d` when you run it, so you know what causing the error.

**Comment by joecue** [comment]
Ivan, thanks for the info.

I ran the "netstat -a" command and cannot find the port specified, in the compose file, in use.

The above output is what I get when I run the "docker-compose up" command whether I use the detach switch or not.

I've tried running docker as an admin, made sure my virus software isn't blocking it.  I just can't seem to get the elasticsearch container to run.

I upgraded my docker toolbox version to the latest and still cannot get the containers to run.  The error I posted above is still the error I'm receiving.

**Comment by dustinrue** [comment]
In this case it's because docker-compose is attempting to map a file but docker wants it to be a directory. I've run into this before but need to find the solution again.

**Comment by zaantar** [comment]
@dustinrue, any luck? :) I keep running into this issue as well.

**Comment by nicoladj77** [comment]
@dustinrue same issue for me, on windows 10

**Comment by aozkan** [comment]
I'm getting the same error, windows 7.

**Comment by ivankristianto** [comment]
Docker on Windows mounted volume need to use absolute path.
can you try change the path for the volume mount config?
sample:
```
volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
```
change to
```
volumes:
      - "${PWD}/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "${PWD}/config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
```

**Comment by cmmarslender** [comment]
No longer able to replicate this on Windows 10. Please reopen if you're still experiencing issues here.
