### ISSUE TITLE
No explanation in docs that hosts must be added manually to hosts file

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/wp-local-docker#18]
In VVV the hosts would get added automatically to the hosts file, however in WP Docker no explanation is given about the host and one could easily assume it would do it. It doesn't appear to do that though, so the readme should be updated to make that more clear in the future.

**Comment by tlovett1** [comment]
I just use localhost. You could certainly add a note about hosts to the readme.

**Comment by sc0ttkclark** [comment]
Looks like this isn't the solution for me yet, I'll wait until it evolves a bit more and it gets some better tools like https://github.com/bradp/vv -- too much heavy lifting to get multiple Docker sites running for different hosts and/or ports (docker-compose.override.yml bug likely also an issue when attempting to override port)

**Comment by jamesgol** [comment]
The PR I just submitted in #20 makes this behave more like @sc0ttkclark wants.  I've been using something similar locally for a while and figured I'd adapt it to something that might be useful for more people.

**Comment by sc0ttkclark** [comment]
That PR fixes the port override issue as well as much of the heavy lifting. I haven't yet tested this for my workflow or usage but I'll look forward to trying your branch @jamesgol even if it isn't ultimately merged for whatever reason.
