### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by jasperf** [10up/wp-local-docker#19]
Would be great if there could be some documentation on how to deploy a local WP Docker setup to the cloud like Digital Ocean or Amazon Web Services.

**Comment by tlovett1** [comment]
This project is really agnostic to deployment methodology.

**Comment by jasperf** [comment]
I see. Sorry to hear that. But will check out other options then.

**Comment by jasperf** [comment]
Found https://github.com/fabrica-wp/fabrica-dev-kit that may work for me. Also Docker based. They use Wordmove for deployment.

**Comment by cr101** [comment]
@jasperf another option is [Laradock](http://laradock.io/)
