### ISSUE TITLE
Can't get this to run

### ISSUE THREAD

**Issue by ashbryant** [10up/wp-local-docker#24]
I followed the instructions, but I can't seem to get this to finish.

Stops on this message ...

`mysql_1          | 2017-05-10T21:40:56.971532Z 0 [Note] End of list of non-natively partitioned tables`

I'm on a mac osx sierra, docker version 17.03.1-ce-mac5 (16048) any ideas why ?

**Comment by thadroe** [comment]
See #13

**Comment by ashbryant** [comment]
Ah ok. Sorry. new to docker :)
