### ISSUE TITLE
Not a directory on fresh install

### ISSUE THREAD

**Issue by juanra** [10up/wp-local-docker#31]
Hi all,

I clone the project on my mac and when I run `docker-compose up` I'm getting the following error:

```
ERROR: for elasticsearch  Cannot start service elasticsearch: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/path/to/the/project/config/elasticsearch/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/9e60c24d9c893b9f3fbbf29d11cc8cec32924446e5f2a1a5ebc6c3fa15bab79e/merged\\\" at \\\"/var/lib/docker/overlay2/9e60c24d9c893b9f3fbbf29d11cc8cec32924446e5f2a1a5ebc6c3fa15bab79e/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```
I fix it removing pointers to specific files, i.e.

```
volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
```
changed to:

```
volumes:
      - "./config/elasticsearch/:/usr/share/elasticsearch/config/"
```

But I want to know what you think.
Thanks and regards,

**Comment by juanra** [comment]
It seems to be something that happens with OSX.  If anyone has any idea how to handle single files in volumes with OSX, I appreciate the feedback.

**Comment by allenmoore** [comment]
Hey @juanra,

I was unable to replicate this issue on a fresh install using the latest from the repo, on MacOS Sierra. I verified that the ElasticSearch container was successfully installed by visiting `http://localhost:9200`, resulting in the following output:
```
{
    name: "bK7f3O4",
    cluster_name: "elasticsearch",
    cluster_uuid: "R6Y-Q4-uQrK_ZZupOqxD_Q",
    version: {
        number: "5.4.0",
        build_hash: "780f8c4",
        build_date: "2017-04-28T17:43:27.229Z",
        build_snapshot: false,
       lucene_version: "6.5.0"
    },
    tagline: "You Know, for Search"
}
```

I also removed the previous local instances, containers, and images that were utilizing the ElasticSearch, and reinstalled fresh instances of each to ensure that previous images were not giving a false response. As with the fresh instance I mentioned above, I was unable to replicate this.

Can you provide additional details about your environment? Are you running the latest version of Docker? Also, can run the following command and let us know what the version number is of the ElasticSearch image:
```
docker image ls
```

Also, can you clone a fresh version of the repo into a new directory, and run `docker-compose up`? If this issue continues, can you copy and paste the entire output after running the command into a new comment?

Thank you,
Allen Moore
