### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by c9dd** [10up/wp-local-docker#33]
Hi Guys, 

Forgive this question as I don't know where else to ask.

I'm setting up an environment using this docker setup and installing WooCommerce. I noticed in the 'status' section it says that I'm missing Soap. How do I get that installed do you have/know any documentation so I could use it to add more in the future if needed? I have tried a couple of things while Googling it, but nothing seems to help.

Thanks

**Comment by tlovett1** [comment]
Just added SOAP to master
