### ISSUE TITLE
Unknown Hang Up on Initial Docker Compose

### ISSUE THREAD

**Issue by kopepasah** [10up/wp-local-docker#34]
After cloning and running the initial `docker-compose up`, the process hangs on 

```
mysql_1          | 2017-05-30T01:59:54.300837Z 0 [Note] End of list of non-natively partitioned tables
```

I posted the full process log [here](https://gist.github.com/kopepasah/47882178912ea4ed211319ebd71f994e), as it is quite large.

**Comment by psorensen** [comment]
see #13. In short, this is Docker running normally. If you want to run it as a background process and not show these messages, you can run `docker-compose up -d` (daemon)

**Comment by kopepasah** [comment]
@psorensen thanks for the info. First time Docker user here. 🤓
