### ISSUE TITLE
MariaDB volumes fail on Windows

### ISSUE THREAD

**Issue by ericmann** [10up/wp-local-docker#4]
This is related to an outstanding issue with the MariaDB container itself. It seems that mounting a volume from the host filesystem throws a lot if INNODB errors within MariaDB itself, which results in an infinite loop of attempting to restart the DB container.

See:
- https://github.com/dockerfile/mariadb/issues/9
- https://github.com/docker-library/mariadb/issues/38

That being said, swapping `mariadb:latest` with `mysql:latest` still results in a runnable stack and everything works as needed on Windows. If anyone can fix MariaDB that'd be stellar, but in the absence of a solid fix, perhaps the base config should use another MySQL variant?

(Note: This error also seems to be the case with Percona, so it's likely a deeper integration error than just a minor bug with MariaDB.)

**Comment by nicholasio** [comment]
I had the same issue on Windows 10. Using docker volumes seems to have resolved the Innodb errors and I managed to get mariadb running, but the container was very slow.

**Comment by ericmann** [comment]
Docker containers _does_ get it running. But you run the risk of losing data between `up`/`down`s and won't have the data mapped to an easily-accessible local directory. If that's the goal (accessibility and persistence) you can still achieve it with `mysql:latest` and still get solid parity between the two implementations. It's just ... not using MariaDB at that point.
