### ISSUE TITLE
Selecting a PHP version to use?

### ISSUE THREAD

**Issue by Viper007Bond** [10up/wp-local-docker#40]
I'm writing a public plugin and to ensure maximum compatibility, I want to write and test it using WordPress's minimum PHP version, 5.2.4.

How can I go about doing this? I see `dockerfiles/php-fpm/Dockerfile` where `7.0` is selected and I see https://hub.docker.com/r/johnpbloch/phpfpm/tags/ where 5.5 is an option (which would be better than nothing), although editing the file doesn't switch the existing Docker container's version (which isn't all that surprising I guess).

So I guess I have two questions:

* How do I switch the PHP version of an existing container? Or do I need to somehow nuke it and rebuild it? Sorry, Docker newbie here.
* Is it possible to use such an old version of PHP instead of 7?

**Comment by tlovett1** [comment]
Hey @Viper007Bond, sorry for the delay. Short answer is yes it's possible but not easy. I have not built a 5.2.4 container for WP Local Docker. However, I have built a 5.2.4 container for another project (won't work out of the box with this). [Here](https://github.com/dockunit/docker-prebuilt/tree/master/php-mysql-phpunit-wordpress/5.2/fpm) are the build scripts/Dockerfile.

Essentially you need to compile PHP 5.2 manually as well as a few other packages e.g. OpenSSL. I actually spent quite a bit of time doing this. The hardest part was building a version of PHPUnit compatible with PHP 5.2.

Perhaps I'll build a new PHP 5.2 container compatible with this project. But honestly, I don't think dealing with 5.2 is really worth the effort anymore. The number of users on less than 5.3 is extremely low.

**Comment by Viper007Bond** [comment]
>  The number of users on less than 5.3 is extremely low.

Good to know. Sounds like I can just target 5.3+ then. It turns out that `composer` for unit tests and stuff doesn't work on PHP 5.2 on Travis CI anyway so that's another reason not to bother.

Thanks for the reply!
