### ISSUE TITLE
ImageMagick

### ISSUE THREAD

**Issue by benoitchantre** [10up/wp-local-docker#43]
I noticed that ImageMagick is not installed.

Thumbnails for PDF files cannot be generated because of the dependency to ImageMagick.

Do you plan to add it?

**Comment by tlovett1** [comment]
@cmmarslender maybe put this in the new Docker image?

**Comment by cmmarslender** [comment]
Latest [phpfpm images](https://github.com/10up/phpfpm-image) now come with ImageMagick.
