### ISSUE TITLE
Define useful constants for development

### ISSUE THREAD

**Issue by benoitchantre** [10up/wp-local-docker#44]
I'm thinking of

- `WP_DEBUG`: `true`
- `SAVEQUERIES`: `true`

Additionally, I think the ones below could be useful too

- `DISALLOW_FILE_EDIT`: `true`
- `WP_POST_REVISIONS`: `false`

I will submit a PR once we agree on the constants.

**Comment by benoitchantre** [comment]
- `WP_CACHE`: `false`

**Comment by benoitchantre** [comment]
Related to #45.

**Comment by Viper007Bond** [comment]
I weakly disagree with turning off `WP_POST_REVISIONS` but otherwise sounds good to me. 👍

**Comment by benoitchantre** [comment]
Thanks for your feedback @Viper007Bond. I understand the reason behind that.
This has not been turned off in #45.

**Comment by Viper007Bond** [comment]
Oops, I failed to notice how old this issue was and that it was only updated, not created. My apologies.

**Comment by cmmarslender** [comment]
This was resolved in #64
