### ISSUE TITLE
Automate WordPress installation

### ISSUE THREAD

**Issue by benoitchantre** [10up/wp-local-docker#45]
Actually, the setup script only creates wp-config.php, then we need to go through the manual install.

We could easily automate the installation of WordPress with WP-CLI. I'm thinking of

- a few prompts to create the first user
- one prompt for the site title
- removal of default contents
- removal of default plugins and themes (keep only the latest theme)
- removal of default widgets
- setting pretty permalinks
- installation of the [Developer](https://wordpress.org/plugins/developer/) plugin

Do you have any other suggestions ?

I can submit a PR once we have discussed this topic.

**Comment by tlovett1** [comment]
I'm open to seeing a PR that does all this.

**Comment by benoitchantre** [comment]
I'll submit a PR, maybe in the next few days.

**Comment by benoitchantre** [comment]
Other improvements included in the PR
- default widgets are replaced by the monster widget
- add useful constants: `DISALLOW_FILE_EDIT`, `WP_DEBUG` and `SAVEQUERIES`

I would like to get more feedbacks on the PR and your opinion about the permalink settings value (actually `/%psotname%/`). Thanks in advance.
