### ISSUE TITLE
Bedrock?

### ISSUE THREAD

**Issue by strarsis** [10up/wp-local-docker#46]
roots.io Bedrock could be interesting for WordPress in Docker -
it treats a WordPress site like a Twelve-Factor app, 
separating configuration, plugins/themes, data.
Composer is used for managing plugins and themes like packages, 
also from many different sources (like download links of premium plugins like ACF PRO):
https://roots.io/twelve-factor-wordpress/

**Comment by etherealite** [comment]
@strarsis I to have been looking for a pre-rolled docker setup for Bedrock. Alas, I'm going to guess that the contributors of this project have Bedrock compatibility pretty low on their list of goals. 

The closest thing I've been able to find so far is [https://github.com/dwnload/wp-docker-bedrock](https://github.com/dwnload/wp-docker-bedrock), which is a straight (but old) fork of this project.

There are a couple of others floating around if you look. Let me know if you find anything.

**Comment by lbngoc** [comment]
I have forked this repo and add some extra features at here https://github.com/lbngoc/php-docker-dev/
To install Bedrock, just run `./bin/setup-bedrock.sh'

**Comment by tlovett1** [comment]
Fork seems like the right move here as I don't see us adding Bedrock.
