### ISSUE TITLE
Don't call it ssh.sh

### ISSUE THREAD

**Issue by etherealite** [10up/wp-local-docker#49]
the script [bin/ssh.sh](https://github.com/dwnload/wp-docker-bedrock/blob/master/bin/ssh.sh) doesn't open an ssh session, therefor calling it ssh.sh is is misnomer.  Why not avoid confusing people and call it __shell.sh__ or something to that degree?

**Comment by tlovett1** [comment]
Agreed. @cmmarslender ?
