### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by windycitymoon** [10up/wp-local-docker#55]
Thanks for providing this useful repository. 

How is your team managing wordpress data persistence using this docker environment? 

Are the database and files stored in data volumes, or are you manually managing the data using git, and manual DB restores?  Would love to hear more about how your team approaches this issue internally.

**Comment by cmmarslender** [comment]
This environment is primarily meant for local development. The database is stored on the host filesystem, and the "wordpress" folder is mounted as the site root inside the docker containers. There isn't any workflow for moving any of this to production, as that is not the goal of the project.

**Comment by windycitymoon** [comment]
Thanks for the reply @cmmarslender. That makes sense.

So how do you manage your data here? I'm worried a little about an inadvertent 'docker-compose down'. Which would destroy everything (if I'm not mistaken). Do you just use git?

**Comment by cmmarslender** [comment]
The MySQL Data files are persisted to [this data folder](https://github.com/10up/wp-local-docker/tree/master/data), even when running `docker-compose down`. The same goes for any files in the webroot - they are all persisted via [the `wordpress` folder](https://github.com/10up/wp-local-docker/tree/master/wordpress).
