### ISSUE TITLE
503 Restricted Network error when importing attachments

### ISSUE THREAD

**Issue by ChrisHardie** [10up/wp-local-docker#56]
I just tried an import via WP-CLI within the web container on a wp-local-docker instance and noted that the attachment import phase was failing with "Failed to import Media" errors for every item. After eliminating some other I attempted to download one of the attachments hosted on the current live site using `curl -I http://...` and got a `HTTP/1.0 503 Restricted Network` result.

I made sure that I didn't have any network  level configuration in place that would block outgoing connections from the container, and the same request works fine from the macOS terminal. Oddly, the behavior is inconsistent, and happens for some URLs and not others, and sometimes differs between an SSL and non-SSL access of the same image/attachment. Here's one with a random image found on the web that consistently fails for me:

```
# curl -I http://s3.amazonaws.com/libapps/accounts/8825/images/shutterstock_130209515.jpg
HTTP/1.0 503 Restricted Network
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 19363
```

while this (SSL version of same file) consistently works:

```
# curl -I https://s3.amazonaws.com/libapps/accounts/8825/images/shutterstock_130209515.jpg
HTTP/1.1 200 OK
x-amz-id-2: cON2D0nLMToEKkEglIIVuAURmZhn8WoHKFmbyenP9CZSBpcZqPZRqPh0UBowCKHwFZnZFCg41Ec=
x-amz-request-id: C9C4E618A29DA5A8
Date: Fri, 25 Aug 2017 15:27:08 GMT
Last-Modified: Wed, 17 Jun 2015 18:21:42 GMT
ETag: "2982a6d99d33b3ff2a9044dc8355bee1"
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 2354005
Server: AmazonS3
```

My understanding is that a given Docker container might be configured to allow some kinds of outbound network connections and not others. Is it possible there's an issue in how the web container is set up that could be causing this? Any suggestions for further troubleshooting?

**Comment by tlovett1** [comment]
Hmmm, not sure on this one. I just ran that curl command successfully from within a container. My guess is either a Docker or network level issue.

**Comment by cmmarslender** [comment]
Going to close this since it has been inactive for a while. If this is still happening with the latest images available on dockerhub and the latest version of wp-local-docker, please provide more details on your OS and any steps I can use to replicate.
