### ISSUE TITLE
Use official elasticsearch docker image.

### ISSUE THREAD

**Issue by rahulsprajapati** [10up/wp-local-docker#59]
Elasticsearch image from docker hub is DEPRECATED.
https://hub.docker.com/_/elasticsearch/
The official image is available at https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Also, elasticsearch latest version is not compatible with elasticpress plugin I think we should use 5.3.x version/tag until the plugin is updated ( https://github.com/10up/ElasticPress/issues/925 )

**Comment by ivankristianto** [comment]
+1 for this
