### ISSUE TITLE
Add ImageMagick

### ISSUE THREAD

**Issue by Viper007Bond** [10up/wp-local-docker#62]
It'd be useful to have ImageMagick for testing purposes.

(I tried to install it myself but I suck at Linux too much to do it.)

**Comment by cmmarslender** [comment]
Duplicate of #43 - I'll see if I can get this added today.

**Comment by cmmarslender** [comment]
Latest [phpfpm images](https://github.com/10up/phpfpm-image) now come with ImageMagick.

**Comment by Viper007Bond** [comment]
Thanks and sorry for not searching first!
