### ISSUE TITLE
Getting error while "docker-compose up"

### ISSUE THREAD

**Issue by BhargavBhandari90** [10up/wp-local-docker#66]
Getting the following error.

```ERROR: error pulling image configuration: Get https://d2iks1dkcwqcbx.cloudfront.net/docker/registry/v2/blobs/sha256/a9/a9a9a2620d666f4dbfb4815f352508b77d5f5adfe7299dfde6d7fa93082a9a46/data?Expires=1515076395&Signature=bMlDXmFYJdKP417mlT3OPcxYjL7Pg0lxeL~BO99KD5a03nCSIPffV20lVgz1Sl5gdU88Y71frfeiTHzcygB8n1CMjMQf6M1e6t~24suNdGoaCz4lVgT9mCDjQG1NiFzi46Ghpg6ZFV9~hEqKiArvgYVx8sIrZUZr1sIWBSZhvhgdT~980DtZFlkTL1BKUdS~lw4p07g89B4xcJ7qKL1v7RTRbh6A1KLsELKgvZzvKH6O2xSPxwe-TLeMRVe~QjztiPiRiEiw-3xsvC0deomIuNJyXjDtSCJ2kCSkUp3VU5xWLynDA8txeh0aVmIvQESSztqXGVFSRqB7WT~~xHpV~g__&Key-Pair-Id=APKAIVAVKHB6SNHJAJQQ: dial tcp: lookup d2iks1dkcwqcbx.cloudfront.net on 127.0.1.1:53: no such host```

**Comment by tlovett1** [comment]
Thanks!
