### ISSUE TITLE
docker.elastic.co offline

### ISSUE THREAD

**Issue by yantei** [10up/wp-local-docker#68]
Unable to use **docker-compose up** command right now because of unavailable docker.elastic.co host:

> Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:5.6.5)...
> ERROR: Get https://docker.elastic.co/v2/: dial tcp: lookup docker.elastic.co on [::1]:53: read udp [::1]:44097->[::1]:53: read: connection refused

**Comment by tlovett1** [comment]
Sorry, nothing we can do if Elastic's container is unavailable.
