### ISSUE TITLE
docker-compose up on mac got some erros

### ISSUE THREAD

**Issue by left2right** [10up/wp-local-docker#74]
Building wpsnapshots
Step 1/6 : FROM 10up/phpfpm
 ---> 62d39cfa546f
Step 2/6 : RUN composer global config repositories.wpsnapshots vcs https://github.com/10up/wpsnapshots
 ---> Using cache
 ---> f3229980a95a
Step 3/6 : RUN composer global require 10up/wpsnapshots:dev-master
 ---> Running in b45c0b0ea8d9
Changed current directory to /root/.composer
Do not run Composer as root/super user! See https://getcomposer.org/root for details

how can i fix this problem? thx

**Comment by tlovett1** [comment]
Did this crash the build?

**Comment by tlovett1** [comment]
@christianc1 can you look at this?

**Comment by christianc1** [comment]
This doesn't crash the build and should be safe to ignore.  The container itself has dropped privileges, and commands are run inside the container.  Attempting to implement a workaround to suppress this message, as far as my understanding goes, would be of no real value.

If this indeed causes issues with bringing the containers up, feel free to reopen.
