### ISSUE TITLE
Error on http://localhost/wp-admin/install.php

### ISSUE THREAD

**Issue by raoden1** [10up/wp-local-docker#75]
I hava the following errors: 

```
Fatal error: Uncaught Error: Call to undefined function load_textdomain() in /var/www/html/wp-admin/includes/admin.php on line 16
--
```
I paste wordpress files into directory with name ./wordpress, when I type http://localhost/wp-admin/install.php
Is depend on wordpress version?

**Comment by Viper007Bond** [comment]
Did you run the setup script? See step 4: https://github.com/10up/wp-local-docker/blob/master/readme.md

That will install WordPress for you.

**Comment by raoden1** [comment]
I read it wrong way. Thanks! Works well
