### ISSUE TITLE
Tables won't create on Multisite (wpms)

### ISSUE THREAD

**Issue by indietravel** [10up/wp-local-docker#76]
WordPress cannot create table for WPMS when trying to create a network.

Using Docker for OSX, version 
```
$ git log -1
commit c1aa147615a3cf0f2f02fa73e72abf44eace9599 (HEAD -> master, origin/master, origin/HEAD)
```

docker-compose.override.yml:
```
version: '3'
services:
  phpfpm:
    extra_hosts:
      - "multisite.local:127.0.0.1"
```

Site runs fine in standard mode. Once activating network mode (subdomains) and adding defines to wp-config.php, the database goes away.

Running database repair outputs: 
```
wp_1_posts: Table 'wordpress.wp_1_posts' doesn't exist
wp_1_comments: Table 'wordpress.wp_1_comments' doesn't exist
wp_1_links: Table 'wordpress.wp_1_links' doesn't exist
wp_1_options: Table 'wordpress.wp_1_options' doesn't exist
wp_1_postmeta: Table 'wordpress.wp_1_postmeta' doesn't exist
wp_1_terms: Table 'wordpress.wp_1_terms' doesn't exist
wp_1_term_taxonomy: Table 'wordpress.wp_1_term_taxonomy' doesn't exist
wp_1_term_relationships: Table 'wordpress.wp_1_term_relationships' doesn't exist
wp_1_termmeta: Table 'wordpress.wp_1_termmeta' doesn't exist
wp_1_commentmeta: Table 'wordpress.wp_1_commentmeta' doesn't exist
```
Looks like there are no permissions for WP to write to the database. Nothing useful in debug.log.

Can anyone duplicate this? Wondering if it's a local-to-me issue or bug.

**Comment by simondowdles** [comment]
If you change your DB user to `root` as opposed to `wordpress`, does that help?

**Comment by kopepasah** [comment]
@indietravel are you still experiencing this issue?

**Comment by indietravel** [comment]
Sorry for the tardy response; just carved out time to test this morning. Confirming that this is no longer an issue for me (latest versions of everything).
