### ISSUE TITLE
mysqld doesn't seem to exist

### ISSUE THREAD

**Issue by mpeshev** [10up/wp-local-docker#83]
Hey everyone, trying to set up the environment as per the standard setup instructions.

Everything seems to be working for the most part - but mysqld does not exist. I don't see any particular errors in the log while up'ing `docker-compose`.  

I can load localhost and the WordPress install.php screen pops up. Can't seem to install WordPress with the login details in the readme. Upon ssh'ing inside of the container, mysqld does not exist (the client is there, but no server).

Installed htop and no process exists, either. Tried to `mysql -h mysql` (or localhost, just in case) and no daemon is started. Can't find mysqld_safe or start a mysql/mysqld service.

I also swapped `mysql:latest` with `mariadb:latest` in the yml config just in case - no luck.

Any tips?

**Comment by simondowdles** [comment]
Where exactly are you trying to access mysql from? If you run `docker-compose up` from the project root, MySQL should be bought up along with other FS layers.

MySQL has it's own container, you won't be able to access it via the phpfpm container. It exposes itself through a service called `mysql` which is also the host name, but only to linked containers that rely on it's presence.

You said the following:

`Tried to mysql -h mysql`

Where did you try that from? From inside the nginx or phpfm containers, or from your local host? If on your local host, then you'd need to run `mysql -h127.0.0.1` with user `wordpress` and password `password`, and not `mysql` as a host name.

**Comment by mpeshev** [comment]
@simondowdles thanks for the heads up.

A couple things:

Tried to connect to the mysql service through my localhost:

```
[nofearinc@localhost devrix]$ mysql -h127.0.0.1 -uwordpress -p
Enter password: 
ERROR 1130 (HY000): Host '172.18.0.1' is not allowed to connect to this MariaDB server
```
I don't have MySQL running on my localhost so I'm not sure why 127.0.0.1 was the target IP. Does the MySQL container come with a predefined static IP I could test with?

In terms of evaluating the problem, I see the install.php dialog from WordPress which indicates that the web server and php-fpm are running. But I cannot connect to the database (and install WordPress). I tried with wordpress as a DB name and wordpress/password for user/pass and it simply can't connect to the database.

The documentation suggest that `mysql` is the host I should use - that didn't work, and neither did localhost or 127.0.0.1 (in case there was a DNS problem). 

That said, the `docker-compose` script indicates that mysql is running - but I can't reach it:

```
mysql_1          | 2018-04-02 11:59:38 140237675571072 [Note] Reading of all Master_info entries succeded
mysql_1          | 2018-04-02 11:59:38 140237675571072 [Note] Added new Master_info '' to hash table
mysql_1          | 2018-04-02 11:59:38 140237675571072 [Note] mysqld: ready for connections.
mysql_1          | Version: '10.2.13-MariaDB-10.2.13+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

**Comment by simondowdles** [comment]
@mpeshev out of interest, if you swap back to MySQL does it work when using 127.0.0.1 as the host?

**Comment by mpeshev** [comment]
@simondowdles just did that, pulled the latest version from the repo (just in case) with `mysql:latest`, same problem (tried localhost, 127.0.0.1, mysql as host names).

Here's the log from docker-compose:

```
mysql_1          | Version: '5.7.21'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:22:55 +0000 "GET /index.php" 302
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:22:56 +0000 "GET /index.php" 302
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:22:56 +0000 "GET /wp-admin/setup-config.php" 200
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:22:57 +0000 "GET /wp-admin/setup-config.php" 200
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:00 +0000 "POST /wp-admin/setup-config.php" 200
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:02 +0000 "GET /wp-admin/setup-config.php" 200
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:06 +0000 "POST /wp-admin/setup-config.php" 500
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:10 +0000 "GET /index.php" 302
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:10 +0000 "POST /wp-admin/setup-config.php" 500
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:10 +0000 "GET /wp-admin/setup-config.php" 200
phpfpm_1         | 172.18.0.6 -  03/Apr/2018:12:23:38 +0000 "POST /wp-admin/setup-config.php" 500

```

**Comment by JayWood** [comment]
@mpeshev I believe the `-p` flag is the only one to not include a space. Also, what OS are you on, I know Windows has some trickery up it's sleeve when it comes to docker.

See my results below:
```
➜  docker-testing git:(master) mysql -u wordpress -p -h 127.0.0.1
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.21 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| wordpress          |
+--------------------+
2 rows in set (0.02 sec)
```

**Comment by mpeshev** [comment]
@JayWood that didn't work, thanks for trying, though!

I run a Fedora 25 Linux. I manage a bunch of servers running LEMP/LAMP on AWS, Digital Ocean, etc. Currently, I use VVV (Vagrant for WP in case you don't use it) here and it works as expected.

Once again, I can't seem to connect:

```
 mysql -u wordpress -p -h 127.0.0.1
Enter password: 
ERROR 1130 (HY000): Host '172.18.0.1' is not allowed to connect to this MySQL server
```

Same goes for the WP install wizard.

I looked this one up and found https://github.com/docker-library/mysql/issues/275 which seems to be a common problem. One of the suggested solutions was looking for DB files in ./data/db which seems legit (3 folders, certificates, etc.) Not sure if it's worth removing that and trying to `docker-compose -d up`?

**Comment by JayWood** [comment]
If you have nothing important in the DB, or if you're just testing, then it won't hurt to delete the db data.

Could you provide a full startup log, maybe a gist? The simplest of things, while seemingly harmless, can provide clues.

**Comment by mpeshev** [comment]
Yeah, I tried that but no luck - still the same.

Here's the gist though - https://gist.github.com/mpeshev/1be532048c8e372c28b49061ada50a5a

We seem to be going in circles so we can close this one if it appears to be an edge case.

**Comment by brandwaffle** [comment]
@mpeshev this might be a long shot, but have you tried http://localhost:8092/? I'm wondering if there's an issue on the application/permission layer in your container that's messing with WP. If that's the case, phpmyadmin should let you see the DB to confirm it's working. The logs sure seem to indicate to me mysqld started up fine.

**Comment by mpeshev** [comment]
@brandwaffle nothing fires up at port 8092.

That said, it may be a permission problem on the mounted drive where Docker is running. After truncating the data folder and switching to mariadb:latest, I see some permission problems with the .pem files which cannot be set correctly - https://gist.github.com/mpeshev/f0281100bab602d4ca42f714e1f3408b

I guess it's a configuration issue, although I run Vagrant there as well and would have liked to avoid it. It's a separate partition that has been allocated for web dev but it may be the reason why it fails. I wonder why nginx and php-fpm don't have problems loading it, but it may be related to mysql's permissions.

Thanks for debugging with me, though - it's appreciated.

**Comment by moraleida** [comment]
I just bumped into this thread looking for something else but since it's still open: the issue with accessing mysql containers in linux hosts is that you need to pass tcp as a protocol so it doesn't try to use a local socket. This works for me on Linux Mint 19:

`    $ mysql -u wordpress -h localhost -p --protocol=tcp`

For completeness, other options that achieve the same thing:

`    $ bin/wp.sh query`

`    $ docker-compose exec mysql mysql -u wordpress -p`
