### ISSUE TITLE
Incorrect / Misleading Resolution in "WP Snapshots is not configured" Error Message

### ISSUE THREAD

**Issue by simondowdles** [10up/wp-local-docker#85]
## The Issue:

If you try to run a WP Snapshots command when WP Snapshots has not been configured yet, you get the following (incorrect) response in the terminal:

`WP Snapshots is not configured, you must run docker-compose wpsnapshots configure <repository>`

Yer, there is no `wpsnapshots` docker-compose command from what I can see. The resolution is to run `./bin/wpsnapshots.[sh/bat] configure` instead, or possibly a `docker-compose exec` command on the `wpsnapshots` container.

## Steps to Reproduce:

1. Clone the repository at git@github.com:10up/wp-local-docker.git
2. Run `docker-compose up` to build the various FS layers and bring up the environment(s)
3. Execute `./bin/wpsnapshots.sh` (assuming Linux / Mac OSX) from the project root
4. Observe the error message and attempt to run the given instruction
5. The resulting error should be `No such command: wpsnapshots`

## Suggested Solution:

- Alter the error message instruction for resolution

**Comment by tlovett1** [comment]
@christianc1 mind looking at this?

**Comment by christianc1** [comment]
Opened https://github.com/10up/wp-local-docker-images/pull/8

**Comment by tlovett1** [comment]
Fixed!

**Comment by simondowdles** [comment]
Whoa, that was speedy, thanks guys!
