### ISSUE TITLE
Add multi vhost would be a great add

### ISSUE THREAD

**Issue by ivankristianto** [10up/wp-local-docker#9]
I do love docker and use it on my local for some projects.
It would be great if we can make it to multi-host, so we can have multiple projects inside it.

I can make a PR for this, if you want.

**Comment by cr101** [comment]
@ivankristianto This is an awesome idea. 
Not having a single docker environment for multiple WordPress sites is the only reason I haven't ditched WAMP yet:
```
+ wp-docker
+ project-1
+ project-2
```

**Comment by dustinrue** [comment]
Could you just map the sites-available directory to a directory with nginx configs for any projects you have?

**Comment by sc0ttkclark** [comment]
In `docker-compose.override.yml` you could try adding another nginx / volumes / conf file mapping (see docker-compose.yml) for default.conf instead of what it is, then you can add a few different hosts/servers there.

**Comment by tlovett1** [comment]
This project is intended to be one project per environment.
