### ISSUE TITLE
Ease custom configurations with Lando

### ISSUE THREAD

**Issue by benoitchantre** [10up/wp-local-docker#94]
I recently discovered [Lando](https://github.com/lando/lando), a local development environment and DevOps tool built on Docker container technology.

I think it would make custom configurations easier to mimic the production environment locally.

> With Lando you can...
>
> * Easily mimic your production environment locally.
> * Standardize your teams dev environments and tooling on OSX, Windows and Linux.
> * Integrate with hosting providers like Pantheon
> * Store all of the above in a version controlled config file called .lando.yml
> * Easily customize or extend tooling, deployment options and basically any other functionality.
> * Free yourself from the tyranny of inferior local development products.

What are your thoughts on this?

**Comment by christianc1** [comment]
Interesting project @benoitchantre.  Can you elaborate on what the issue is, or what you're suggesting for this project?

**Comment by benoitchantre** [comment]
@christianc1 This idea come from my personal experience with Docker and the fact that there are many different production environment. The closer your local environment to the production, the better.

Without a strong understanding of Docker, it feels difficult to adjust the configuration to mimic your production environment. I tried to use Apache instead of Nginx, but I gave up quickly because I had not enough time to learn how to properly customize the environment.

With Lando, the configuration file looks a lot simplier, there's also a lot of documentation and recipes. To my eyes, it looks more efficient to create a local environment.

Note: I discovered Lando this week-end at a conference and haven't tried it at the moment.

**Comment by kopepasah** [comment]
Hey @benoitchantre, thanks for the suggestion with Lando! Looks like a pretty awesome tool.

Seems like you were only sharing your thoughts on Lando (which is awesome!). As such, I am going to close out this issue. If you are experiencing issues with `wp-local-docker` while running Lando, feel free to open another issue!
