### ISSUE TITLE
NGINX Error Log - not found

### ISSUE THREAD

**Issue by qbattersby** [10up/wp-local-docker#96]
Hey,

Running this on Win 10 - specifically through WSL using the daemon as a host so it routes back through to the Windows install. 

I cant seem to get past docker-compose up due to this error; help? :(

`
nginx_1          | nginx: [emerg] open() "/var/log/nginx/error.log" failed (2: No such file or directory)
nginx_1          | nginx: [emerg] open() "/var/log/nginx/error.log" failed (2: No such file or directory)
wapp_nginx_1 exited with code 1
`

**Comment by dana-ross** [comment]
You need to clone the repo using Git for Windows in order to have the permissions set correctly. WSL can be used after that point.

**Comment by ironland** [comment]
@daveross is this still the case? Currently lots of people (and probably even more in the future) are hoping to be able to use only WSL when developing in Win 10 and therefore might not have nor want Git for Windows installed. Could there be an easy way to fix this instead of having to use Git for Windows?

**Comment by qbattersby** [comment]
Would also love to see this setup so we can clone with git in WSL.

**Comment by mwarf** [comment]
I cloned this repo with git for windows and received the same errors with Nginx. Windows 10 x64 Pro - was hoping to also develop with WSL, but can't seem to get past the nginx issue.

**Comment by qbattersby** [comment]
I've been using Varying Vagrant Vagrants instead. Which is great but
doesn't isolate sites

Quinn Battersby
e// quinn@battersby.ca
t// 226-338-1659
w// www.qbattersby.com
