### ISSUE TITLE
Nginx container is not starting

### ISSUE THREAD

**Issue by stefanosaittamrf** [10up/wp-local-docker#97]
Runnig `docker-compose up` on a just cloned repo give me this error on the `wp-local-docker_nginx_1` container.

```
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint wp-local-docker_nginx_1 (df6489b1d02353c44134d10de72162c67e01f743433e4eab265d7406fb65188d): Error starting userland proxy: Bind for 0.0.0.0:443: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
```

Any help?

**Comment by cmmarslender** [comment]
You have something else already bound to port 443. If you have other docker containers running that bind 443, you need to stop them. Alternatively, it could be another local development environment running.
