### ISSUE TITLE
Error establishing a database connection - authentication method unknown to the client

### ISSUE THREAD

**Issue by kakoma** [10up/wp-local-docker#99]
Hi team,
Thanks for the amazing project. On setting this up though, going to localhost returns this error: **Error establishing a database connection** 
Turning on debug in the WordPress installation produces this  in  `debug.log` :

```
{dateTime} PHP Warning:  mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password] in /path/here/wp-includes/wp-db.php on line 1531
```

The root cause of that is this change in MySQL 8: 
https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/

A quick corrective action is to downgrade MySQL version by changing:
    `image: mysql:latest`
to
    `image: mysql:5.7`
in `docker-compose.yml`
The issue only arose recently because the _mysql:latest_ tag was recently updated to point to MySQL 8

**Comment by pattonwebz** [comment]
I experienced this same issue recently in another stack. Can confirm a downgrade to a non-`latest` mysql was the fix.

**Comment by kakoma** [comment]
@pattonwebz Yes, the downgrade worked for me and I believe it'll work for many. When `latest`  started pointing to `8.x`, this issue arose and as you've mentioned, it will show up in different stacks depending on their support for the new default authentication plugin.

**Comment by pattonwebz** [comment]
Hey @kakoma, 

Looks like this was fixed by: https://github.com/10up/wp-local-docker/commit/558ce442a4a54df7fb6ae8688419f204299015c7 a little while ago :)

**Comment by kakoma** [comment]
@pattonwebz Ohh cool. I might have been on a different branch then. Thanks!!!
